package com.exeception;

public class ArrayoutofboundDemo2 {
public static void main(String[] args) {
	int[] a = new int[5];
	try {
		for(int i = 0; i <= 5; i++) {
			a[i] = i;
			System.out.println(a[i]);
	
		}
	} catch (Exception e) {
		e.printStackTrace();
	}
	finally {
		System.out.println("this code is generated by Paresh Kakadiya");
		System.out.println("mo no:9099592962");
	}
}
}
